REDIRECT_URI = "urn:ietf:wg:oauth:2.0:oob"
PICASA_URL = "https://picasaweb.google.com/data/"
TOKEN_URL = "https://www.googleapis.com/oauth2/v4/token"
ENDPOINT_URL = "https://picasaweb.google.com/data/feed/api/user/"
TOKEN_PATH = ".save.json"
